package org.openapitools.model

import java.util.Objects
import com.fasterxml.jackson.annotation.JsonProperty
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid
import io.swagger.v3.oas.annotations.media.Schema

/**
 * Data for the authorisation of the payment. 
 * @param authorisationCode The authorisation code generated by the issuer for an authorised payment. 
 * @param cvvResponseData Additional response data containing the CVV response. 
 */
data class PaymentInstrumentOutputCardAuthorisation(

    @get:Pattern(regexp="^[0-9a-zA-Z]{2,6}$")
    @get:Size(min=2,max=6)
    @Schema(example = "12345", description = "The authorisation code generated by the issuer for an authorised payment. ")
    @field:JsonProperty("authorisationCode") val authorisationCode: kotlin.String? = null,

    @get:Pattern(regexp="^[0-9A-F]{6}$")
    @get:Size(min=6,max=6)
    @Schema(example = "422800", description = "Additional response data containing the CVV response. ")
    @field:JsonProperty("cvvResponseData") val cvvResponseData: kotlin.String? = null
) {

}

